# Generated by Django 5.2.12 on 2026-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('manual', '업무 매뉴얼'), ('history', '과거 업무 처리'), ('notice', '공지사항'), ('weekly', '주간업무')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
