# Generated by Django 5.2.12 on 2026-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_tag_alter_post_tags_post_tags_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags_v2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='wiki.tag'),
        ),
    ]
